# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cl.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cnt_0_0/design_1_cnt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cnt_0_0 || ORIG_REF_NAME==design_1_cnt_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cnt_0_1/design_1_cnt_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cnt_0_1 || ORIG_REF_NAME==design_1_cnt_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cnt_0_2/design_1_cnt_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cnt_0_2 || ORIG_REF_NAME==design_1_cnt_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cnt_0_3/design_1_cnt_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cnt_0_3 || ORIG_REF_NAME==design_1_cnt_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xishi_0_0/design_1_xishi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xishi_0_0 || ORIG_REF_NAME==design_1_xishi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jiepai_0_0/design_1_jiepai_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jiepai_0_0 || ORIG_REF_NAME==design_1_jiepai_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_0/design_1_huo4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_0 || ORIG_REF_NAME==design_1_huo4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_1/design_1_huo4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_1 || ORIG_REF_NAME==design_1_huo4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_2/design_1_huo4_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_2 || ORIG_REF_NAME==design_1_huo4_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_3/design_1_huo4_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_3 || ORIG_REF_NAME==design_1_huo4_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_4/design_1_huo4_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_4 || ORIG_REF_NAME==design_1_huo4_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_5/design_1_huo4_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_5 || ORIG_REF_NAME==design_1_huo4_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo4_0_6/design_1_huo4_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo4_0_6 || ORIG_REF_NAME==design_1_huo4_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_compar_0_0/design_1_compar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_compar_0_0 || ORIG_REF_NAME==design_1_compar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xishi2_0_0/design_1_xishi2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xishi2_0_0 || ORIG_REF_NAME==design_1_xishi2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_5_0_0/design_1_clock_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_5_0_0 || ORIG_REF_NAME==design_1_clock_5_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_0/design_1_huo2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_0 || ORIG_REF_NAME==design_1_huo2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_10_1_0/design_1_clock_10_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_10_1_0 || ORIG_REF_NAME==design_1_clock_10_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_1/design_1_huo2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_1 || ORIG_REF_NAME==design_1_huo2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_2/design_1_huo2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_2 || ORIG_REF_NAME==design_1_huo2_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_3/design_1_huo2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_3 || ORIG_REF_NAME==design_1_huo2_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_4/design_1_huo2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_4 || ORIG_REF_NAME==design_1_huo2_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_5/design_1_huo2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_5 || ORIG_REF_NAME==design_1_huo2_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huo2_0_6/design_1_huo2_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huo2_0_6 || ORIG_REF_NAME==design_1_huo2_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_amount_0_0/design_1_amount_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_amount_0_0 || ORIG_REF_NAME==design_1_amount_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huotwo_0_0/design_1_huotwo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huotwo_0_0 || ORIG_REF_NAME==design_1_huotwo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_yu4_0_0/design_1_yu4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_yu4_0_0 || ORIG_REF_NAME==design_1_yu4_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
